Update four-dot-one-to-four-dot-two.md
encounted the error as below during upgrade and able to fix it via above addition
app_user@marketplace:~/productions2$ rails spree:install:migrations
rails aborted!
NameError: uninitialized constant SpreeI18n::Config
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
/home/app_user/productions2/config/initializers/spree.rb:20:in `block in <main>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spree_core-4.2.0.rc4/lib/spree/core.rb:59:in `config'
/home/app_user/productions2/config/initializers/spree.rb:12:in `<main>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:666:in `block in load_config_initializer'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/notifications.rb:182:in `instrument'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:665:in `load_config_initializer'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `each'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `block in <class:Engine>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `each'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
/home/app_user/productions2/config/environment.rb:5:in `<main>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application.rb:339:in `require_environment!'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application.rb:523:in `block in run_tasks_blocks'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:644:in `block (4 levels) in <class:Engine>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/command.rb:48:in `invoke'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/app_user/productions2/bin/rails:9:in `<top (required)>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/home/app_user/productions2/bin/spring:15:in `require'
/home/app_user/productions2/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
NameError: uninitialized constant SpreeI18n::Config
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
/home/app_user/productions2/config/initializers/spree.rb:20:in `block in <main>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spree_core-4.2.0.rc4/lib/spree/core.rb:59:in `config'
/home/app_user/productions2/config/initializers/spree.rb:12:in `<main>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:666:in `block in load_config_initializer'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/notifications.rb:182:in `instrument'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:665:in `load_config_initializer'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `each'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `block in <class:Engine>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `each'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
/home/app_user/productions2/config/environment.rb:5:in `<main>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application.rb:339:in `require_environment!'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application.rb:523:in `block in run_tasks_blocks'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:644:in `block (4 levels) in <class:Engine>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/command.rb:48:in `invoke'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/app_user/productions2/bin/rails:9:in `<top (required)>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/home/app_user/.rvm/gems/ruby-2.7.2/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/home/app_user/productions2/bin/spring:15:in `require'
/home/app_user/productions2/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => railties:install:migrations => db:load_config => environment
(See full trace by running task with --trace)